site_name: RansNet Documentation
site_url: https://docs.ransnet.com
site_description: Technical guides for using RansNet products.
site_author: RansNet Singapore Pte Ltd
copyright: "&copy; 2026 RansNet Singapore Pte Ltd. All Rights Reserved."

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - toc.follow
  logo: images/RansNet_logo.png
  favicon: images/RansNet_logo.png


extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:support@ransnet.com
      name: support@ransnet.com
    - icon: fontawesome/solid/globe
      link: https://www.ransnet.com
      name: www.ransnet.com
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Getting Started:
    - start/index.md
    - Product Overview: start/overview.md
    - mfusion Overview:
      - Features: start/mfusion/features.md
      - Security: start/mfusion/security.md
      - Admin: start/mfusion/admin.md
    - Device Setup:
      - Bootstrapping: start/device/bootstrap.md
      - Provisioning: start/device/provision.md
      - Onboarding: start/device/onboard.md
      - Hardening: start/device/harden.md
  - Device Monitoring:
    - monitor/index.md
    - Dashboard: monitor/dashboard.md
    - Hosts: monitor/hosts.md
    - Topology: monitor/topo.md
    - Wireless: monitor/wifi.md
    - Netflow: monitor/netflow.md
    - Alerts: monitor/alerts.md
    - Settings: monitor/settings.md
  - Network Settings:
    - config/index.md
    - Interfaces:
      - Ethernet: config/iface/ethernet.md
      - VLAN: config/iface/vlaniface.md
      - Bridge: config/iface/bridge.md
      - WWAN: config/iface/wwan.md
      - PPPoE: config/iface/pppoe.md
      - Switchport: config/iface/switchport.md
      - WiFi as WAN: config/iface/wifiwan.md
    - DHCP: config/dhcp.md
    - DNS Rewrite: config/dnsrewrite.md
    - Routing:
      - Static Routes: config/route/static.md
      - Network Groups: config/route/groups.md
      - Dynamic(OSPF): config/route/ospf.md
      - Dynamic(BGP): config/route/bgp.md
    - VRRP: config/vrrp.md
    - Wireless: config/wifi.md
    - Tracking: config/tracking.md
  - SD-WAN:
    #- sdwan/index.md
    - VPN Overlay:
      - VPN Protocols: sdwan/vpn/vpnintro.md
      - VPN Topology: sdwan/vpn/topology.md
      - VPN Instance: sdwan/vpn/instance.md
    - Multi-WAN: sdwan/mwan.md
    #  - Traffic Steering: sdwan/traffic/pbr.md
    - Traffic Shaping: sdwan/qos.md
  - Firewall & Security:
    #- security/index.md
    - Firewall:
      - Overview: security/firewall/overview.md
      - Policies: security/firewall/policies.md
      - Objects: security/firewall/objects.md
      - Templates: security/firewall/templates.md
    - Web Filtering: security/webfilter.md
    #- Netflow Analyzer: security/netflow.md
    #- Log Collector: security/log.md
    #- RADIUS Server: security/radius.md
  #- System & Tools:
  #  - DNS: system/dns.md
  #  - NTP: system/ntp.md
  #  - SNMP: system/snmp.md
  #  - Syslog: system/syslog.md
  #  - Tools:
  #    - Speed Test: tools/speedtest.md
  #    - Packet Capture: tools/packetcapture.md
  #    - Traceroute: tools/traceroute.md
  #    - Ping: tools/ping.md
  - HotSpot Gateway:
    - hotspot/index.md
  - Use Cases:
    - WAN Failover: cases/wanfailover.md
    - Cloud SD-WAN: cases/cloudsdwan.md
    - Layer-2 SD-WAN: cases/l2vpn.md
    - VRF over SD-WAN: cases/vrf.md
    #- Wi-Fi over SD-WAN: cases/wifi.md
    - Crew WiFi Hotspot: cases/crewwifi.md
  #- Q&A:
  #  - qa/index.md
  - API Documentation:
    #- API Setup: api/setup.md
    - Hotspot API: api/hotspot.md
    #- Monitoring API: api/rmm.md
    - Syslog API: api/syslog.md
    - WISPr API: api/wispr.md
    - NetFlow API: api/netflow.md
